name: 'setup-docker-remote-tls'
description: 'Setup TLS and docker environment for remote deployment'
branding:
  icon: briefcase
  color: blue
inputs:
  tls_key:
    description: 'Raw content of the private key (~/.docker/key.pem)'
    required: true
  tls_ca:
    description: 'Raw content of the certificate (~/.docker/ca.pem)'
    required: true
  tls_cert:
    description: 'Raw content of the certificate (~/.docker/cert.pem)'
    required: true
  tcp_host:
    description: 'TCP hostname WITH port e.g. myhost.example.com:2376'
    required: false
runs:
  using: 'node16'
  main: 'lib_main/index.js'
  post: 'lib_post/index.js'
  post-if: 'success()'
